### ISSUE TITLE
CentOS support

### ISSUE THREAD

**Issue by fulv** [plone/ansible-playbook#30]
This may open a can of worms, but I was wondering if there is any interest in supporting other platforms, to wit CentOS.  If so, I can make a pull request of a branch I have with a few changes that make the playbook work on CentOS 7.  It was pretty easy, for the most part it was just a matter of using yum instead of apt.  A couple of roles will not work, and compatible replacements will be needed, such as fail2ban and unattended-upgrades.

**Comment by fulv** [comment]
Also, the `firewall.yml` playbook can't be used as is, because `ufw` is ubuntu-specific.

**Comment by smcmahon** [comment]
Juan Pablo has already got the plone_server role working with CentOS, and that should help. Also, the vagrant setup is now rigged to support multiple test boxes.

I'd say, go for it in a branch. If it works and seems maintainable, we'll merge it. I suggest you limit the support to the equivalent of the most recent Ubuntu LTS, which is to say the latest version likely to be a popular choice for a new cloud server. We don't want to get in the business of supporting lots of versions.

A warning, there's now a little bit of trickiness in the varnish install to deal with the fact that more recent debian/ubuntu package using systemd rather than an init script. That's what's supporting VCL 3 and 4.
